<?php
/**
 * Plugin Name: Sample Widget
 * Description: This is a sample widget for testing things
 * Version: 1.0.0
 */

 //use WP_Widget;
 
 class Sample_Widget extends WP_Widget {
 	public function __construct()
    {
	    $id_base = 'Sample_Widget';
	    $name = 'Sample Widget';
	    $widget_options = ['description' => 'it is a widget that does something good'];
	    $control_options = [];
	    
	    parent::__construct($id_base, $name, $widget_options, $control_options);
    }
    function form($instance)
    {
    	//echo '<pre>';
    	//print_r($instance);
    	$title = $instance['title'] ?? "new title";
	    $text = $instance['text'] ?? "new text";
    	?>
	    <p>
		    <label for="<?= $this->get_field_id('title') ?>">Title</label>
		    <input type="text" id="<?= $this->get_field_id('title') ?>"
		           name="<?= $this->get_field_name('title')?>" value="<?= esc_attr($title)?>">
		    <label for="<?= $this->get_field_id('text') ?>">Text</label>
		    <input type="text" id="<?= $this->get_field_id('text') ?>"
		           name="<?= $this->get_field_name('text')?>" value="<?= esc_attr($text)?>">
	    </p>
		<?php
    }
    function update($new_instance, $old_instance)
    {
	    //$instance = $old_instance;
	    //$new_instance['title'] = strip_tags($new_instance['title']);
	    return $new_instance;
    }
    function widget($args, $instance)
    {
    	
    	extract($args);
    	//print_r($args);
	
	    echo
		    $before_widget .
		    
		    $before_title . ($instance['title']) . $after_title .
		    
		    ($instance['text'] ?? 'widget has no text') .
		    
		    $after_widget;
	    
	    
	    //parent::widget($args, $instance); // TODO: Change the autogenerated stub
	    //extract($args);
	    //echo '<pre>';
	    //print_r($args);
    }
 }
 
 // This function is a most have for the widget to work
 function register_sample_widget() {
 	register_widget('Sample_Widget');
 }
 add_action('widgets_init', 'register_sample_widget');